#!/bin/bash
error=0

if [ -z "$1" ]; then
    echo "This script is used to pretty-print all XML files inside ODF or OOXML package file."
    echo
	echo "Usage:"
	echo "	`basename "$0"` [filename]"
	exit
fi

error_handle()
{
    error=1
    echo "Error: $1"
    rm -rf $TMPDIR || echo "Cleanup failure!"
    exit 1
}


TMPDIR=$(mktemp -d -t ci-XXXXXXXXXX)
FILENAME=$(basename "$1")

unzip -D "$1" -d $TMPDIR > /dev/null || error_handle "unzip fails!"
chmod -R 744 $TMPDIR

find $TMPDIR -type f -name "*.xml" -o -type f -name "*.rels" | while read filename; do
	xmllint --format "${filename}" > "${filename}2" || error_handle "xmllint fails!"
	mv "${filename}2" "${filename}"  > /dev/null || error_handle "mv fails!"
done

# Check while loop errors
if [ "$error" -gt 0 ]; then
    echo "${error}!"
    echo ":("
    exit 1
fi

pushd $TMPDIR > /dev/null
zip "$FILENAME" -r . > /dev/null || error_handle "zipping fails!"
popd > /dev/null

mv "$TMPDIR/$FILENAME" "$1"  > /dev/null
rm -rf $TMPDIR || echo "Cleanup failure"
